### ISSUE TITLE
Completion malfunctioning

### ISSUE THREAD

**Issue by aerosol** [sanmiguel/helpex.vim#1]
yo, found a few issues:
1. [x] `Enum.` `C-x C-o` doen't show `map` suggestion even if the user continues typing
2. [x] `Enum.m` `C-x C-o` shows `map` suggestion, removes `Enum.` from the buffer
3. ~~`m` `C-x C-o` crashes~~
4. [x] `m` `C-x C-o` attempts to complete based on an empty string
5. [x] `s:parse_suggestion(base, suggestion)` fails when the suggestion is `//2`

Moving picture of the above: https://asciinema.org/a/9ieye8bjkk5o0anorot6ehco3

**Comment by sanmiguel** [comment]
Forgive the edit; added checkboxes :)

**Comment by aerosol** [comment]
:ok_hand:

**Comment by sanmiguel** [comment]
Tried to do asciinema but for some reason it won't render the omnicompl menu for me...

**Comment by sanmiguel** [comment]
`m` `C-x C-o` crashing is actually multiple problems:
-  [x] `m` `C-x C-o` attempts to complete based on an empty string
- [x] `s:parse_suggestion(base, suggestion)` fails when the suggestion is `//2`

**Comment by sanmiguel** [comment]
This made me realise another issue #5 but I'll get to that another time.

**Comment by sanmiguel** [comment]
Question @aerosol : in general (when using other langs' omnifuncs) if you do the equivalent of typing `Enum.` `<C-x><C-o>` and start typing does it narrow down the matches in the menu?

**Comment by sanmiguel** [comment]
Mine always completes the first in the list and if I try to delete any chars to correct the menu goes away.

**Comment by sanmiguel** [comment]
Ah, perhaps this is `completeopts += longest` ?

**Comment by sanmiguel** [comment]
Yup, it's that, plus something else... Fix incoming.
